### ISSUE TITLE
raise 'yolo'

### ISSUE THREAD

**Issue by thomasjoulin** [KrauseFx/fastlane-plugin-clean_testflight_testers#5]
Is this line supposed to be here? https://github.com/KrauseFx/fastlane-plugin-clean_testflight_testers/blob/d6814e4b361d9710dac93db0d05ed5d35b4bfbb7/lib/fastlane/plugin/clean_testflight_testers/actions/clean_testflight_testers_action.rb#L54

It seems the script stops after the first removal...

**Comment by KrauseFx** [comment]
oha, no no, this shouldn't happen, so sorry for including this, will push a new version right away!

**Comment by KrauseFx** [comment]
Alright, pushed https://github.com/KrauseFx/fastlane-plugin-clean_testflight_testers/commit/b2b8248107f20f9761c9d36f2553c3e583922665
